# Generated by Django 5.1.1 on 2024-10-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('일반', '일반 문의'), ('정보', '고객 정보 변경'), ('불편', '불편 민원'), ('안내', '결과 안내')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsels', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Counsel',
                'verbose_name_plural': 'Counsels',
                'ordering': ['-created_at'],
            },
        ),
    ]
